name: "Demo workflow, runs on push"

on:
  push:
    branches:
      - master

jobs:
  singlejob:
    name: "MemCheck compilation and deployment to prod"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Show GITHUB_REF"
      run: echo ${{GITHUB_REF}}

    - name: "Show a secret correctly: it gets redacted"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}"      

    - name: "Show a secret with an error in the script: a mean to have it shown in the GUI"
      # Here I forget to use quotes
      # This will make the action fail because there is a quote in the secret string
      run: echo ${{secrets.NOT_TOO_CONFIDENTIAL}}
