name: "Demo workflow, runs on push"

on:
  push:
    branches:
      - master

jobs:
  singlejob:
    name: "MemCheck compilation and deployment to prod"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Show the directory tree"
      run: tree /F /A

    - name: "Show a secret correctly: it gets redacted"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}"      

    - name: "Show a secret with an error in the script: a mean to have it shown in the GUI"
      # Here I forget to use quotes
      run: echo ${{secrets.NOT_TOO_CONFIDENTIAL}}
